//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badge.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Badge.Resources.ColorResource", typeof(ColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #476486.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #5f8cb4.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #70a1c1.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #a29bfe.
        /// </summary>
        public static string Numling {
            get {
                return ResourceManager.GetString("Numling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2ed573.
        /// </summary>
        public static string Pilt {
            get {
                return ResourceManager.GetString("Pilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fdcb6e.
        /// </summary>
        public static string Pusling {
            get {
                return ResourceManager.GetString("Pusling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ff7f50.
        /// </summary>
        public static string Senior {
            get {
                return ResourceManager.GetString("Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #747d8c.
        /// </summary>
        public static string Seniorvæbner {
            get {
                return ResourceManager.GetString("Seniorvæbner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ff5252.
        /// </summary>
        public static string Tumling {
            get {
                return ResourceManager.GetString("Tumling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4a69bd.
        /// </summary>
        public static string Væbner {
            get {
                return ResourceManager.GetString("Væbner", resourceCulture);
            }
        }
    }
}
